### ISSUE TITLE
长图 3m 变 17m …

### ISSUE THREAD

**Issue by theweeeknd** [lecepin/image-border#1]
![1](https://user-images.githubusercontent.com/84619641/169810722-8ca984f5-b795-4a41-b0f9-f7ca9bbc8600.png)
![2](https://user-images.githubusercontent.com/84619641/169810733-4248b5e7-132c-4dce-bb90-387638d5b249.png)

**Comment by lecepin** [comment]
已支持 webp/jpg 可以高效压缩
